# Generated by Django 3.2.3 on 2021-05-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewBaggages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('imgname', models.CharField(max_length=100)),
                ('objname', models.CharField(max_length=50)),
                ('xmaxi', models.IntegerField(blank=True, null=True)),
                ('ymaxi', models.IntegerField(blank=True, null=True)),
                ('xmini', models.IntegerField(blank=True, null=True)),
                ('ymini', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
